### PR TITLE
Stbranch

### PR DESCRIPTION
**Pull request by strangestar**

### CODE REVIEW

**Comment by strangestar** [comment]
Related to: #33 #30

**Comment by strangestar** [comment]
Primary changes:
-Newly created Bugs are associated with a Hunt 
-Newly created Hunts are associated with a Company
-Users are able to "join" a company

**Comment by strangestar** [comment]
If no one has anything to say, I will close this in the interest of time.

**Comment by fadyibrahim** [comment]
Well done Stuart.

**Pull request merged**
