### PR TITLE
Html edits

### PR DESCRIPTION
**Pull request by docksmur**
redirect login success to bugs page instead of welcome page and added login and signup links to welcome page

### CODE REVIEW

**Comment by docksmur** [comment]
tests fail after adding a login requirement for users to see the bug page. I could remove that line or I could edit the test to login first I suppose. which way would be better

**Comment by strangestar** [comment]
Editing the test to expect failure when not logged in would make sense.

**Comment by docksmur** [comment]
tests were edited so they expect a redirect to a login page. I think this is ready for merging now

**Comment by fadyibrahim** [comment]
Alright, well done guys. Please try to comment the code so that others can work off your committed code. Thank you.

**Pull request merged**
